```{r}
health_df = read.csv("insurance.csv")
head(health_df)

View(health_df)
```


```{r}
str(health_df)
```


```{r}
sum(is.na(health_df))

```

```{r}
dim(health_df)
```


```{r}
sum(duplicated(health_df))

require(ggplot2)
```


```{r}
health_df <- distinct(health_df)

```


```{r}
names(health_df)
```

UNIVARIATE ANALYSIS: 
```{r}
# Age

summary(health_df$age)

```

```{r}

hist(health_df$age)

boxplot(health_df$age)

```



```{r}
plot(quantile(health_df$age, seq(0,1, 0.01)))

```


```{r}
table(health_df$sex)

```


```{r}
sex_df <- group_by(health_df, sex) %>% summarise(average_charges = mean(charges))

ggplot(sex_df, aes(x = sex , y = average_charges)) + geom_col(fill = 'darkgreen', color = 'red')

```


```{r}
# BMI
summary(health_df$bmi)
```

```{r}
quantile(health_df$bmi,seq(0,1,0.01))
```


```{r}
plot(quantile(health_df$bmi,seq(0,1,0.01)))

```


```{r}
health_df$bmi[which(health_df$bmi > 46.4112)] <- 46.4112

```


```{r}
plot(quantile(health_df$bmi,seq(0,1,0.01)))

```


```{r}
summary(health_df$bmi)

```


```{r}
summary(health_df$children)

```


```{r}
plot(quantile(health_df$children,seq(0,1,0.01)))

```


```{r}
table(health_df$children)
```


```{r}
hist(health_df$children)

```


```{r}
table(health_df$smoker)

```


```{r}
smoker_df <- group_by(health_df, smoker) %>% summarise(average_charges = mean(charges))

smoker_df
ggplot(smoker_df, aes(x = smoker , y = average_charges)) + geom_col(fill = 'darkgreen', color = 'red')

```


```{r}
table(health_df$region)

```


```{r}
region_df <- group_by(health_df, region) %>% summarise(average_charges = mean(charges))

region_df
ggplot(region_df, aes(x = region , y = average_charges)) + geom_col(fill = 'darkgreen', color = 'red')

```


```{r}
summary(health_df$charges)

```

```{r}
quantile(health_df$charges,seq(0,1,0.01))
```


```{r}
plot(quantile(health_df$charges,seq(0,1,0.01)))

```


```{r}
health_df$charges[which(health_df$charges > 48537.797)] <- 48537.797

plot(quantile(health_df$charges,seq(0,1,0.01)))

```


```{r}
summary(health_df)

```


```{r}
require(dummies)

final_data <- dummy.data.frame(health_df)

View(final_data)
```

```{r}
corr_mat = round(cor(final_data),2)

View(corr_mat)
```

```{r}
require(corrplot)

corrplot(corr_mat, method = 'color', type = 'upper')
```



```{r}
set.seed(111)

i <- sample(nrow(final_data), 0.75 * nrow(final_data))

trn_df <- final_data[i,]

val_df <- final_data[-i,]
```


```{r}
lrm_1 <- lm(charges ~ ., data = trn_df)

summary(lrm_1)
```


```{r}
lrm_2 <- step(lrm_1)

summary(lrm_2)
```


VARIANCE INFLATION FACTOR
```{r}
require(car)

sort(vif(lrm_2))
```



```{r}
val_df$predict_charges <- predict(lrm_2, val_df)

```


```{r}
View(val_df)
```


```{r}
require(forecast)

accuracy(val_df$predict_charges, val_df$charges)
```


```{r}
Rsq_val <- cor(val_df$predict_charges , val_df$charges)^2

Rsq_val

```
###########################################


